# _config-examples/single-stage/compose/circle.yml

version: 2

jobs:
  job1:
    docker:
      - image: docker/compose:1.23.2
    environment:
      CACHE_IMAGE: mjhea0/docker-ci-cache

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull image from docker hub
          command: docker pull $CACHE_IMAGE:latest || true
      - run:
          name: Build Docker images
          command: docker-compose build
      - run:
          name: Spin up containers
          command: docker-compose up -d
      - run:
          name: Run flake8
          command: docker-compose exec web flake8
      - run:
          name: Run tests
          command: docker-compose exec web python manage.py test
      - run:
          name: Log in to docker hub
          command: docker login -u $REGISTRY_USER -p $REGISTRY_PASS
      - run:
          name: Push to docker hub
          command: docker push $CACHE_IMAGE:latest


workflows:
  version: 2

  tests_to_run:
    jobs:
    - job1
