# .gitlab-ci.yml

image: docker:stable
services:
  - docker:dind

variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay
  CACHE_IMAGE: mjhea0/docker-ci-cache

stages:
  - build

docker-build:
  stage: build
  script:
    - docker pull $CACHE_IMAGE:latest || true
    - docker build --cache-from $CACHE_IMAGE:latest --tag $CACHE_IMAGE:latest .
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker push $CACHE_IMAGE:latest
