# _config-examples/multi-stage/.travis.yml

os: linux
dist: bionic

env:
  global:
    CACHE_IMAGE: mjhea0/docker-ci-cache
    DOCKER_BUILDKIT: 1

before_install:
  - set -e
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic
  - docker info

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

script:
  - docker build
      --target base
      --cache-from $CACHE_IMAGE:base
      --tag $CACHE_IMAGE:base
      --file ./Dockerfile.multi
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
  - docker build
      --cache-from $CACHE_IMAGE:base
      --cache-from $CACHE_IMAGE:stage
      --tag $CACHE_IMAGE:stage
      --file ./Dockerfile.multi
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."

after_success:
  - docker push $CACHE_IMAGE:base
  - docker push $CACHE_IMAGE:stage
