# _config-examples/single-stage/.travis.yml

sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: mjhea0/docker-ci-cache

before_script:
  - docker pull $CACHE_IMAGE:latest || true

script:
  - docker build --cache-from $CACHE_IMAGE:latest --tag $CACHE_IMAGE:latest .

after_success:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push $CACHE_IMAGE:latest
